site_name: PyTexas Runbooks
repo_url: https://github.com/pytexas/runbooks
repo_name: pytexas/runbooks
theme:
  name: material
  logo: assets/images/favicon.png
  custom_dir: overrides
  features:
    - navigation.tracking
    - toc.integrate
    - toc.follow
  palette:
    primary: blue
    accent: yellow
copyright: Copyright &copy; 2024 - PyTexas Foundation

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Conference:
    - Overview: conference/index.md
    - Master Timeline: conference/runbooks/conference-master-timeline.md
    - Conference Chair:
      - The Role: conference/roles/conf-chair.md
      - Committee Workflow: conference/runbooks/conference-committee-runbook.md
      - Kickoff Meeting: conference/runbooks/kickoff-meeting.md
      - Next-Year Planning: conference/runbooks/next-year-planning.md
      - Run of Show: conference/runbooks/run-of-show.md
      - Day-of Operations: conference/runbooks/day-of-operations-guide.md
      - Post-Event: conference/runbooks/post-event.md
      - Onboarding a New Lead: conference/runbooks/onboarding-new-lead.md
    - Speaker Committee:
      - Speaker Chair: conference/roles/speaker-chair.md
      - Committee Workflow: conference/runbooks/speaker-committee-runbook.md
      - Call for Proposals: conference/runbooks/cfp.md
      - Keynote: conference/runbooks/keynote.md
    - Finance Committee:
      - Finance Chair: conference/roles/fin-chair.md
      - Committee Workflow: conference/runbooks/finance-committee-runbook.md
      - Budget Planning: conference/runbooks/budget-planning-template.md
      - Sponsorship: conference/runbooks/sponsorship.md
      - Opportunity Grants: conference/runbooks/grants.md
      - Registration: conference/runbooks/registration.md
    - Marketing Committee:
      - Marketing Chair: conference/roles/mark-chair.md
      - Committee Workflow: conference/runbooks/marketing-committee-runbook.md
      - Swag: conference/runbooks/swag.md
    - Venue Committee:
      - Venue Chair: conference/roles/venue-chair.md
      - Committee Workflow: conference/runbooks/venue-committee-runbook.md
      - Venue: conference/runbooks/venue.md
      - A/V Vendor: conference/runbooks/av.md
      - Catering: conference/runbooks/catering.md
      - Networking Event: conference/runbooks/network-event.md
      - Day-of Supplies: conference/runbooks/day-of-supplies.md
      - Volunteers: conference/runbooks/volunteers.md
    - Community Committee:
      - Community Chair: conference/roles/community-chair.md
      - Committee Workflow: conference/runbooks/community-committee-runbook.md
      - Discord and Hybrid: conference/runbooks/discord.md
      - Code of Conduct: conference/runbooks/coc.md
      - Attendee Feedback: conference/runbooks/feedback.md
  - Virtual Meetup:
    - Documentation: meetup/index.md
    - Roles:
      - Host: meetup/roles/host.md
      - Backstage/Moderator: meetup/roles/backstage.md
      - Speaker Engagement: meetup/roles/speaker-engagement.md
    - Runbooks:
      - CFP Review: meetup/runbooks/cfp-review.md
      - Create Run of Show Document: meetup/runbooks/create-run-of-show.md
      - Meetup Night Of Workflow: meetup/runbooks/meetup-night-of.md
  - Community Discord:
    - Documentation: community/index.md
    - Coffee Chats: community/runbooks/coffee-chats.md
    - Sprint Nights: community/runbooks/sprint-nights.md
  - Contributors Guide: contribute.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pytexas
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jNPAbcNukj
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/pytexas-foundation
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@PyTexas/
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@pytexas
    - icon: fontawesome/brands/meetup
      link: https://www.meetup.com/pro/pytexas
    - icon: fontawesome/brands/github
      link: https://github.com/pytexas
