[project]
name = "runbooks"
version = "0.1.0"
description = "PyTexas Foundation Runbooks"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.29",
    "mkdocs-material-extensions>=1.3.1",
]